-- 创建书签表
CREATE TABLE IF NOT EXISTS `bookmark` (
  `id` BIGINT PRIMARY KEY AUTO_INCREMENT COMMENT '书签ID',
  `user_id` BIGINT COMMENT '所属用户ID',
  `folder_id` BIGINT COMMENT '所属文件夹ID',
  `title` VARCHAR(200) COMMENT '书签标题',
  `url` VARCHAR(500) COMMENT '书签URL',
  `icon` VARCHAR(500) DEFAULT NULL COMMENT '书签图标',
  `description` TEXT DEFAULT NULL COMMENT '书签描述',
  `id_delete` INT(5) DEFAULT NULL COMMENT '是否逻辑删除',
  `created_time` DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_time` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='书签表';
